name: Update Key

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  update_key:
    runs-on: ubuntu-latest
    
    steps:
      - name: Fetch daily key
        id: fetch_key
        run: |
          key=$(curl -sSL "https://raw.githubusercontent.com/SilentIsPrivate/SilentHubKeys/main/daily_key.txt")
          echo "::set-output name=key::$key"
      
      - name: Use the key in your script
        run: |
          # Replace this command with the one to use the key in your script
          echo "Fetched key: ${{ steps.fetch_key.outputs.key }}"
